# Usages

## Overview

- This page shows a general pipeline for analyzing LiP data via lipana
- The example data is a truncated search report from DIA-NN, which has 3 experiment conditions and 3 replicates per condition, and only 1000 proteins are kept
- The example files are in "path_to/LiPAna/example_data"

In [ ]:
import gzip
import shutil
from pathlib import Path

workspace = Path(".").resolve().parents[1].joinpath("example_data")
print("current workspace:", str(workspace))
# Unzip gzipped files
for file in workspace.glob("*.gz"):
    with gzip.open(file, "rb") as f_in:
        with open(file.with_suffix(""), "wb") as f_out:
            shutil.copyfileobj(f_in, f_out)

current workspace: /home/lourh/Project-LiPDIA/project_src/LiPAna/example_data

In [2]:
import sys

sys.path.append(str(workspace.parent))
import lipana

In [3]:
from time import sleep

import polars as pl

## Define the experiment layout

- At first, an experiment layout is required for annotating the expected report
- Below will introduce two approaches to do so

1. Load a text file which stores the experiment layout, like the following ("replicate" can be omitted)

|  run | condition | replicate |
| ---: | --------: | --------: |
| run1 |      ctrl |         1 |
| run2 |      ctrl |         2 |
| run3 |      ctrl |         3 |
| run4 |      exp1 |         1 |
| run5 |      exp1 |         2 |
| run6 |      exp1 |         3 |
| run7 |      exp2 |         1 |
| run8 |      exp2 |         2 |

In [4]:
import lipana

exp_layout = lipana.ExperimentLayout.from_file(workspace.joinpath("experiment_layout.txt"))
print("The input file is:")
exp_layout.exp_df

The input file is:

shape: (9, 3)
┌─────────────────────────────────┬───────────┬───────────┐
│ run                             ┆ condition ┆ replicate │
│ ---                             ┆ ---       ┆ ---       │
│ str                             ┆ str       ┆ i64       │
╞═════════════════════════════════╪═══════════╪═══════════╡
│ 20240331_YSJ-HY_2d5_100-400ng_… ┆ H2d5_Y100 ┆ 1         │
│ 20240331_YSJ-HY_2d5_100-400ng_… ┆ H2d5_Y100 ┆ 2         │
│ 20240404_YSJ-HY_2d5_100-400ng_… ┆ H2d5_Y100 ┆ 3         │
│ 20240331_YSJ-HY_5_100-400ng_A_… ┆ H5_Y100   ┆ 1         │
│ 20240331_YSJ-HY_5_100-400ng_B_… ┆ H5_Y100   ┆ 2         │
│ 20240404_YSJ-HY_5_100-400ng_C_… ┆ H5_Y100   ┆ 3         │
│ 20240331_YSJ-HY_25_100-400ng_A… ┆ H25_Y100  ┆ 1         │
│ 20240331_YSJ-HY_25_100-400ng_B… ┆ H25_Y100  ┆ 2         │
│ 20240404_YSJ-HY_25_100-400ng_C… ┆ H25_Y100  ┆ 3         │
└─────────────────────────────────┴───────────┴───────────┘

2. Init by passing a run-to-condition map

In [5]:
import lipana

exp_layout = lipana.ExperimentLayout.from_run_to_condition_map(
    {
        "20240331_YSJ-HY_2d5_100-400ng_A_90min_stdDIA-HomeMade_Slot1-12_1_5154": "H2d5_Y100",
        "20240331_YSJ-HY_2d5_100-400ng_B_90min_stdDIA-HomeMade_Slot1-13_1_5155": "H2d5_Y100",
        "20240404_YSJ-HY_2d5_100-400ng_C_90min_stdDIA-HomeMade_Slot1-24_1_5206": "H2d5_Y100",
        "20240331_YSJ-HY_5_100-400ng_A_90min_stdDIA-HomeMade_Slot1-14_1_5157": "H5_Y100",
        "20240331_YSJ-HY_5_100-400ng_B_90min_stdDIA-HomeMade_Slot1-15_1_5158": "H5_Y100",
        "20240404_YSJ-HY_5_100-400ng_C_90min_stdDIA-HomeMade_Slot1-28_1_5210": "H5_Y100",
        "20240331_YSJ-HY_25_100-400ng_A_90min_stdDIA-HomeMade_Slot1-19_1_5163": "H25_Y100",
        "20240331_YSJ-HY_25_100-400ng_B_90min_stdDIA-HomeMade_Slot1-20_1_5164": "H25_Y100",
        "20240404_YSJ-HY_25_100-400ng_C_90min_stdDIA-HomeMade_Slot1-34_1_5220": "H25_Y100",
    }
)

print("This results in the same experiment layout as the previous example, because replicate is incremented from 1")
exp_layout.exp_df

This results in the same experiment layout as the previous example, because replicate is incremented from 1

shape: (9, 3)
┌─────────────────────────────────┬───────────┬───────────┐
│ run                             ┆ condition ┆ replicate │
│ ---                             ┆ ---       ┆ ---       │
│ str                             ┆ str       ┆ i64       │
╞═════════════════════════════════╪═══════════╪═══════════╡
│ 20240331_YSJ-HY_2d5_100-400ng_… ┆ H2d5_Y100 ┆ 1         │
│ 20240331_YSJ-HY_2d5_100-400ng_… ┆ H2d5_Y100 ┆ 2         │
│ 20240404_YSJ-HY_2d5_100-400ng_… ┆ H2d5_Y100 ┆ 3         │
│ 20240331_YSJ-HY_5_100-400ng_A_… ┆ H5_Y100   ┆ 1         │
│ 20240331_YSJ-HY_5_100-400ng_B_… ┆ H5_Y100   ┆ 2         │
│ 20240404_YSJ-HY_5_100-400ng_C_… ┆ H5_Y100   ┆ 3         │
│ 20240331_YSJ-HY_25_100-400ng_A… ┆ H25_Y100  ┆ 1         │
│ 20240331_YSJ-HY_25_100-400ng_B… ┆ H25_Y100  ┆ 2         │
│ 20240404_YSJ-HY_25_100-400ng_C… ┆ H25_Y100  ┆ 3         │
└─────────────────────────────────┴───────────┴───────────┘

## Load a search report

- In this step, the example report will be loaded and annotated
  - A DIA-NN report can be from either executing DIA-NN alone or from the FragPipe that uses DIA-NN to process DIA data
  - For Spectronaut report, there are some required columns and a template of report setting can be generated by the following command: `lipana.report.export_sn_report_setting("path_to_store_the_setting_file.rs")`

### First load FASTA file(s)

- FASTA files should be first loaded and parsed for further use for report annotation
- `lipana.parse_fasta` will read one or more FASTA files and return a `ParsedFasta` object
  - `fasta_path` can be a path points to a FASTA or a list of paths (`fasta_path=some_path` or `fasta_path=[path1, path2]`)
  - `contam_fasta_path`: this parameter will be useful to strictly exclude potential contaminants. The species of any protein entries in the given file will be annotated as "Contam" instead of its original species, including those presented in `fasta_path`
  - `contaminations`: a list of additional protein entries can be given here, and this parameter can also work alone if `contam_fasta_path` is `None`

In [6]:
parsed_fasta = lipana.parse_fasta(
    fasta_path=workspace.joinpath("human_yeast_contam.fasta"),
    contam_fasta_path=workspace.joinpath("contam.fasta"),
    contaminations=None,
    gen_species_to_concat_seqs=True,  # This parameter is useful to annotate species of peptides via a whole protein sequence map, but is time-consuming
    workspace=workspace,
    resume=True,
    write_parsed_fasta=True,
)

### Load and annotate a search report

- In this step, a search report will be loaded and annotated via the already initialized `ExperimentLayout` and `ParsedFasta`

In [7]:
# Below two methods have the same paramters
# lipana.DIANNReport.load_search_report(...)
# lipana.SpectronautReport.load_search_report(...)

# Here will load a DIA-NN search report as an example, and show a subset of available parameters
report = lipana.DIANNReport.load_search_report(
    workspace.joinpath("example_diann_report.txt"),
    exp_layout=exp_layout,
    parsed_fasta=parsed_fasta,
    do_species_annotation=True,  # Set this to True if the experiment has multiple species (and they should also be presented in FASTA files)
    pre_annotation_filter=(
        (pl.col("Q.Value") < 0.01)
        & (pl.col("Lib.PG.Q.Value") < 0.01)
        & (pl.col("Protein.Group").is_not_null())
        & (pl.col("Precursor.Quantity").is_not_null())
        & (pl.col("Precursor.Quantity") > 1.1)
    ),  # The filters defined here will be applied to the report after loading immediately, and here the 5 rules are default for DIA-NN (if this parameter is not given, these rules will be applied); for Spectronaut, they are (
    #     (pl.col("PG.ProteinGroups").is_not_null())
    #     & (pl.col("FG.Quantity").is_not_null())
    #     & (pl.col("FG.Quantity") > 1.1)
    # )
    post_annotation_filter=None,  # This parameter can be used to filter the report after annotation
    restricted_cut_sites=("K", "R"),
    expand_to_cut_site_level=True,  # This will make each cut site one row, which means each precursor row will be duplicated
    # modification_map=None,  # This parameter can be either None or a map from software used modification to UniMod. By default, DIA-NN report has None because it use UniMod as default; for `SpectronautReport`, this parameter has a default value as {
    #     "[Acetyl (Protein N-term)]": "(UniMod:1)",
    #     "[Carbamidomethyl (C)]": "(UniMod:4)",
    #     "[Oxidation (M)]": "(UniMod:35)",
    # }
)
# The variable `report` is now a `SearchReport` object, and basic annotations have been done
report

Search report object with main report shape: (113057, 81)
Number of quantification data: 0
Number of statistics results: 0
Workspace: /home/lourh/Project-LiPDIA/project_src/LiPAna/example_data

## Prepare quantification matrices

- A newly generated `SearchReport` object will only store a preprocessed search report and some meta-data
- In this section, some quantification matrices will be added to this object
- The quantification can be just a pivot of the report, or do quantification aggregation via topN or maxLFQ

### Use raw reported quantity values

- This will do a simple conversion to get a quantification matrix by using software reported raw quantity values as cells, and is useful to get a precursor or protein group level matrix
- This step also shows how to attach a customized quantification report to the main report manually via `attach_quant_data` method

In [8]:
quant_data = report.attach_quant_data(
    lipana.convert_long_report_to_wide(
        report,
        index_col="precursor",
        column_col="run",
        value_col="precursor_quantity",
        do_log_scale=2,
        pl_filter=(
            ~pl.col("mapped_species_from_peptide").str.contains(";", literal=True)
        ),  # This parameter filters out those peptides mapped to multiple species
        do_unique=True,
    ),
    entry_level="precursor",  # These two parameters will be the name of this quantification report, and can be used to retrieve it from the main report object
    quant_method="precursor_quantity",
)

# To retrieve this object from the main report object, use the following command
quant_data = report.get_quant_data("precursor", "precursor_quantity")

### maxLFQ or topN

- The maxLFQ and topN methods share the same interface by calling `SearchReport.construct_and_attach_quant_data` method, and have some convenient designs to handle more complicated scenarios
- The following examples will only use "maxlfq", and topN can be configured by setting `method="top3"`, `method="top1"`, ...

#### Peptide matrix from precursor MS2 via maxLFQ

In [9]:
# This will do maxLFQ on precursor quantities to get a peptide level matrix
quant_data = report.construct_and_attach_quant_data(
    quant_name="peptide_quant_by_maxlfq_from_prec",
    method="maxlfq",
    filter_condition=(~pl.col("mapped_species_from_peptide").str.contains(";", literal=True)),
    run_col="run",
    primary_entry_col="stripped_peptide",
    low_level_entry_col="precursor",
    base_quant_col="precursor_quantity",
    require_expansion=False,
    concat_entry_after_expansion=None,
    remove_below_threshold=1.1,
    quant_input_name=None,
    attach_quant_input=False,
)

MaxLFQ estimation via iq for /tmp/tmp96yb1iyo.txt
Removing low intensities...

Output to /tmp/tmp96yb1iyo.txt-iq_output.txt

Command: --sample SampleIds --primary PrimaryIds --secondary AggregationIds --quant BaseQuant /tmp/tmp96yb1iyo.txt

Sample column:
    SampleIds
Protein column:
    PrimaryIds
Ion column(s):
    AggregationIds
Quant column:
    BaseQuant

Using 4 threads ...

# lines read (excluding headers)      = 55844
# quantitative values after filtering = 55844

# samples  = 9
# proteins = 9577
nrow = 55844, # proteins = 9577, # samples = 9
Using 95 threads...
0%
5%
10%
15%
20%
25%
30%
35%
41%
46%
52%
58%
64%
69%
74%
80%
85%
90%
Completed.

#### Peptide matrix from prec MS1, prec MS2, and fragments, via maxLFQ

In [10]:
# The quantities of base level entries can also be from multiple sources
# The following example will use maxLFQ to aggregate quantities from three levels: precursor MS1, precursor MS2, and fragments
quant_data = report.construct_and_attach_quant_data(
    quant_name="peptide_quant_by_maxlfq_from_multi",
    method="maxlfq",
    filter_condition=(~pl.col("mapped_species_from_peptide").str.contains(";", literal=True)),
    run_col="run",
    primary_entry_col="stripped_peptide",
    low_level_entry_col=("precursor", "precursor", "Fragment.Info"),
    base_quant_col=("precursor_quantity", "precursor_quantity_ms1", "Fragment.Quant.Raw"),
    require_expansion=(False, False, ";"),
    concat_entry_after_expansion=None,
    remove_below_threshold=1.1,
    quant_input_name=None,
    attach_quant_input=False,
)

MaxLFQ estimation via iq for /tmp/tmps9jzxjsm.txt

Command: --sample SampleIds --primary PrimaryIds --secondary AggregationIds --quant BaseQuant /tmp/tmps9jzxjsm.txt

Sample column:
    SampleIds
Protein column:
    PrimaryIds
Ion column(s):
    AggregationIds
Quant column:
    BaseQuant

Using 4 threads ...

# lines read (excluding headers)      = 701484
# quantitative values after filtering = 701484

# samples  = 9
# proteins = 9577

Removing low intensities...

nrow = 701484, # proteins = 9577, # samples = 9
Using 95 threads...
0%
5%
10%
16%
21%
27%
33%
38%
44%
49%
54%
61%
66%
72%
79%
84%
90%
97%
Completed.

Output to /tmp/tmps9jzxjsm.txt-iq_output.txt

#### Non-restricted cut site from precursor MS2

In [11]:
# Sometimes, the quantity values should be aggregated from a filtered report
# Except to directly filter the report, call quantification function, and attach the matrix to main report
# The following example will generate a cut site level matrix by only using semi-specific peptides
quant_data = report.construct_and_attach_quant_data(
    quant_name="nonrestricted_cut_site_by_maxlfq_from_prec",
    method="maxlfq",
    filter_condition=(
        (~pl.col("mapped_species_from_peptide").str.contains(";", literal=True))
        & (pl.col("peptide_enzymatic_specificity") == "semi_specific")
    ),
    run_col="run",
    primary_entry_col="cut_site",
    low_level_entry_col="precursor",
    base_quant_col="precursor_quantity",
    require_expansion=False,
    concat_entry_after_expansion=None,
    remove_below_threshold=1.1,
    quant_input_name=None,
    attach_quant_input=False,
)

Command: --sample SampleIds --primary PrimaryIds --secondary AggregationIds --quant BaseQuant /tmp/tmp0bwzp8nt.txt

Sample column:
    SampleIds
Protein column:
    PrimaryIds
Ion column(s):
    AggregationIds
Quant column:
    BaseQuant

Using 4 threads ...

# lines read (excluding headers)      = 51767
# quantitative values after filtering = 51767

# samples  = 9
# proteins = 7146
nrow = 51767, # proteins = 7146, # samples = 9
Using 95 threads...
1%
6%
11%
16%
21%
26%
31%
36%
41%
46%
51%
56%
61%
66%
71%
77%
84%
89%
Completed.

MaxLFQ estimation via iq for /tmp/tmp0bwzp8nt.txt
Removing low intensities...

Output to /tmp/tmp0bwzp8nt.txt-iq_output.txt

### Utilities on quantification report

- The quantification matrix generated from the above sections is actually an object `EntryQuantificationReport`, which has many handful functions

In [12]:
# If the generated object is not explicitly assigned to a variable, can use the following way to get from main report object
quant_data = report.get_quant_data("precursor", "precursor_quantity")

# The following three methods will attach new columns to the dataframe stored in the quantification report object
quant_data.calc_cv(cond="all", min_reps=3, temp_reverse_log_scale=2, new_colname_pattern="{cond}_cv_{min_reps}reps")
quant_data.count_detected_replicates(new_colname_pattern="{cond}_detected_reps")
quant_data.calc_ratio(
    base_cond="H5_Y100",
    is_log=True,
    temp_reverse_log_scale=2,
    div_method="agg_and_divide",
    agg_method="mean",
    new_colname_pattern="ratio_{cond1}_to_{cond2}",
)

shape: (10_303, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ precursor ┆ 20240331_ ┆ 20240331_ ┆ 20240331_ ┆ … ┆ H25_Y100_ ┆ H2d5_Y100 ┆ ratio_H25 ┆ ratio_H2 │
│ ---       ┆ YSJ-HY_25 ┆ YSJ-HY_25 ┆ YSJ-HY_2d ┆   ┆ detected_ ┆ _detected ┆ _Y100_to_ ┆ d5_Y100_ │
│ str       ┆ _100-400n ┆ _100-400n ┆ 5_100-400 ┆   ┆ reps      ┆ _reps     ┆ H5_Y100   ┆ to_H5_Y1 │
│           ┆ g_B…      ┆ g_A…      ┆ ng_…      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 00       │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ i8        ┆ i8        ┆ f32       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆ f32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ LPAEVEIPK ┆ 14.434139 ┆ 13.938183 ┆ 13.895041 ┆ … ┆ 3         ┆ 3         ┆ 0.145257  ┆ -0.38295 │
│ NVDIS/2   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ YFQAPSDYR ┆ 13.567189 ┆ 13.716377 ┆ null      ┆ … ┆ 2         ┆ 0         ┆ NaN       ┆ NaN      │
│ /2        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ KAVSNEELK ┆ 17.286247 ┆ 17.239571 ┆ 17.427143 ┆ … ┆ 3         ┆ 3         ┆ 0.083509  ┆ 0.12777  │
│ /2        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ LKELPDTVG ┆ 14.283339 ┆ 14.581157 ┆ null      ┆ … ┆ 3         ┆ 0         ┆ 2.860971  ┆ NaN      │
│ ELR/2     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ LYDKTENDI ┆ 16.569562 ┆ 16.734969 ┆ 16.672663 ┆ … ┆ 3         ┆ 3         ┆ -0.144281 ┆ -0.02922 │
│ K/2       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ LMADELER/ ┆ 16.904433 ┆ null      ┆ null      ┆ … ┆ 1         ┆ 0         ┆ NaN       ┆ NaN      │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ SQGQLNEKP ┆ 13.006362 ┆ null      ┆ null      ┆ … ┆ 1         ┆ 0         ┆ NaN       ┆ NaN      │
│ LPEGWEMR/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ SGYFQFNK/ ┆ null      ┆ 14.248252 ┆ null      ┆ … ┆ 1         ┆ 0         ┆ NaN       ┆ NaN      │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ELVDKATNV ┆ null      ┆ null      ┆ null      ┆ … ┆ 1         ┆ 0         ┆ NaN       ┆ NaN      │
│ VMNYSEIES ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ K/3       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ SMPDPDKAS ┆ 11.271508 ┆ null      ┆ null      ┆ … ┆ 1         ┆ 0         ┆ NaN       ┆ NaN      │
│ AC(UniMod ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ :4)PGQAT/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

- Because main report and quantification report are related, the annotation and filtering of quantification report can be done by borrowing data from the main report
- The following method will return a new dataframe instead of updating the dataframe stored in the object

In [13]:
report.get_quant_data(
    entry_name="precursor",
    quant_name="precursor_quantity",
    main_df_entry_filter=(
        (~pl.col("mapped_species_from_peptide").str.contains(";", literal=True))
        & (pl.col("peptide_enzymatic_specificity") == "semi_specific")
    ),
    quant_df_filter=None,
    annotation_cols="protein_group",
)

shape: (4_761, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ precursor ┆ 20240331_ ┆ 20240331_ ┆ 20240331_ ┆ … ┆ H2d5_Y100 ┆ ratio_H25 ┆ ratio_H2d ┆ protein_ │
│ ---       ┆ YSJ-HY_25 ┆ YSJ-HY_25 ┆ YSJ-HY_2d ┆   ┆ _detected ┆ _Y100_to_ ┆ 5_Y100_to ┆ group    │
│ str       ┆ _100-400n ┆ _100-400n ┆ 5_100-400 ┆   ┆ _reps     ┆ H5_Y100   ┆ _H5_Y100  ┆ ---      │
│           ┆ g_B…      ┆ g_A…      ┆ ng_…      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ i8        ┆ f32       ┆ f32       ┆          │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ LPAEVEIPK ┆ 14.434139 ┆ 13.938183 ┆ 13.895041 ┆ … ┆ 3         ┆ 0.145257  ┆ -0.382955 ┆ Q04438   │
│ NVDIS/2   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ YFQAPSDYR ┆ 13.567189 ┆ 13.716377 ┆ null      ┆ … ┆ 0         ┆ NaN       ┆ NaN       ┆ Q08380   │
│ /2        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MALHGEGSG ┆ 19.113167 ┆ 18.821163 ┆ 19.034922 ┆ … ┆ 3         ┆ -0.03314  ┆ -0.092298 ┆ P23248   │
│ EEKGK/3   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSQSGPFTY ┆ 14.815426 ┆ 14.937284 ┆ 15.032842 ┆ … ┆ 3         ┆ -0.148558 ┆ -0.087604 ┆ P38797   │
│ K/2       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ VVDNGSGMC ┆ 15.680193 ┆ 15.928102 ┆ null      ┆ … ┆ 2         ┆ 2.466893  ┆ -1.632221 ┆ Q562R1   │
│ (UniMod:4 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ )K/2      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ IFEGTHENP ┆ null      ┆ null      ┆ null      ┆ … ┆ 0         ┆ NaN       ┆ NaN       ┆ O75165   │
│ ELIWNDNSR ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /3        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DSVTSPDMD ┆ 10.174464 ┆ null      ┆ null      ┆ … ┆ 0         ┆ NaN       ┆ NaN       ┆ Q14C86   │
│ EITHGA/2  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ TTDGKLPEV ┆ null      ┆ 14.081129 ┆ null      ┆ … ┆ 0         ┆ NaN       ┆ NaN       ┆ P50454   │
│ TK/2      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ C(UniMod: ┆ 10.988452 ┆ null      ┆ null      ┆ … ┆ 0         ┆ NaN       ┆ NaN       ┆ P51659   │
│ 4)NTIAPNA ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSR/2     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ SMPDPDKAS ┆ 11.271508 ┆ null      ┆ null      ┆ … ┆ 0         ┆ NaN       ┆ NaN       ┆ Q52LW3   │
│ AC(UniMod ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ :4)PGQAT/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
quant_data = report.get_quant_data("precursor", "precursor_quantity")
quant_data.attach_annotation_via_entry(
    "protein_group", persistent=False
)  # Set `persistent` to True will update the dataframe stored in the object
quant_data.filter_entry_by_main_report(
    main_report_filter=(~pl.col("mapped_species_from_peptide").str.contains(";", literal=True))
    & (pl.col("peptide_enzymatic_specificity") == "semi_specific")
)

shape: (4_761, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ precursor ┆ 20240331_ ┆ 20240331_ ┆ 20240331_ ┆ … ┆ H25_Y100_ ┆ H2d5_Y100 ┆ ratio_H25 ┆ ratio_H2 │
│ ---       ┆ YSJ-HY_25 ┆ YSJ-HY_25 ┆ YSJ-HY_2d ┆   ┆ detected_ ┆ _detected ┆ _Y100_to_ ┆ d5_Y100_ │
│ str       ┆ _100-400n ┆ _100-400n ┆ 5_100-400 ┆   ┆ reps      ┆ _reps     ┆ H5_Y100   ┆ to_H5_Y1 │
│           ┆ g_B…      ┆ g_A…      ┆ ng_…      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 00       │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ i8        ┆ i8        ┆ f32       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆ f32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ LPAEVEIPK ┆ 14.434139 ┆ 13.938183 ┆ 13.895041 ┆ … ┆ 3         ┆ 3         ┆ 0.145257  ┆ -0.38295 │
│ NVDIS/2   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ YFQAPSDYR ┆ 13.567189 ┆ 13.716377 ┆ null      ┆ … ┆ 2         ┆ 0         ┆ NaN       ┆ NaN      │
│ /2        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MALHGEGSG ┆ 19.113167 ┆ 18.821163 ┆ 19.034922 ┆ … ┆ 3         ┆ 3         ┆ -0.03314  ┆ -0.09229 │
│ EEKGK/3   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ GSQSGPFTY ┆ 14.815426 ┆ 14.937284 ┆ 15.032842 ┆ … ┆ 3         ┆ 3         ┆ -0.148558 ┆ -0.08760 │
│ K/2       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ VVDNGSGMC ┆ 15.680193 ┆ 15.928102 ┆ null      ┆ … ┆ 3         ┆ 2         ┆ 2.466893  ┆ -1.63222 │
│ (UniMod:4 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ )K/2      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ IFEGTHENP ┆ null      ┆ null      ┆ null      ┆ … ┆ 1         ┆ 0         ┆ NaN       ┆ NaN      │
│ ELIWNDNSR ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /3        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DSVTSPDMD ┆ 10.174464 ┆ null      ┆ null      ┆ … ┆ 1         ┆ 0         ┆ NaN       ┆ NaN      │
│ EITHGA/2  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ TTDGKLPEV ┆ null      ┆ 14.081129 ┆ null      ┆ … ┆ 1         ┆ 0         ┆ NaN       ┆ NaN      │
│ TK/2      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ C(UniMod: ┆ 10.988452 ┆ null      ┆ null      ┆ … ┆ 1         ┆ 0         ┆ NaN       ┆ NaN      │
│ 4)NTIAPNA ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSR/2     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ SMPDPDKAS ┆ 11.271508 ┆ null      ┆ null      ┆ … ┆ 1         ┆ 0         ┆ NaN       ┆ NaN      │
│ AC(UniMod ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ :4)PGQAT/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Statistics

- lipana has many built-in functions to do different things for statistics, and the statistic pipeline can be customized by chaining built-in functions and customized functions
- Additionally, a packed function has three pre-defined pipelines embedded
- This section will show how to use this function to do tests with any of the three pre-defined pipelines

### Select minimum p-value

- This pipeline will do tests on the base entry level, and each target entry will have the test result selected with the min p-value among its associated base entries
- For example, tests can be done on precursor level, and each protein can have multiple precursors. In this case, for one protein, the FC, p-value, and others will be the same as the one precursor that has min p-value among all precursors that belong to this protein

#### Example: select precursor with min p-value for protein

In [15]:
design = lipana.ComparisonDesign(exp_layout, (("H2d5_Y100", "H5_Y100"), ("H25_Y100", "H5_Y100")))
print(f"{design.pairwise_comparisons = }")

stats = lipana.do_stats_pipeline_pairwise(
    qdf=report.get_quant_data(entry_name="precursor", quant_name="precursor_quantity").df,
    main_df=report.df,
    design=design,
    target_entry_col="protein_group",
    base_entry_col="precursor",
    group_entry_col=None,
    pipeline="sel_min_p",
    return_chains=False,
)
sleep(0.1)
print("First 5 rows of the result:")
stats.head(5)

design.pairwise_comparisons = (('H2d5_Y100', 'H5_Y100'), ('H25_Y100', 'H5_Y100'))

Quantification file: /tmp/tmp86tb32qj.txt
All defined comparison pairs: c("H2d5_Y100", "H5_Y100")
Available comparison pairs: c("H2d5_Y100", "H5_Y100")
Comparing H2d5_Y100 vs H5_Y100
Output to /tmp/tmp86tb32qj.txt-limma_output.txt
Quantification file: /tmp/tmphsksx7m6.txt
All defined comparison pairs: c("H25_Y100", "H5_Y100")
Available comparison pairs: c("H25_Y100", "H5_Y100")
Comparing H25_Y100 vs H5_Y100
Output to /tmp/tmphsksx7m6.txt-limma_output.txt

First 5 rows of the result:

shape: (5, 13)
┌────────────┬───────────┬──────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ precursor  ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ protein_g ┆ row_sign ┆ group_sig ┆ adj_pvalu │
│ ---        ┆ imma      ┆ ---      ┆ ---       ┆   ┆ roup      ┆ ---      ┆ n         ┆ e_exp_wis │
│ str        ┆ ---       ┆ f64      ┆ f64       ┆   ┆ ---       ┆ f64      ┆ ---       ┆ e         │
│            ┆ f64       ┆          ┆           ┆   ┆ str       ┆          ┆ f64       ┆ ---       │
│            ┆           ┆          ┆           ┆   ┆           ┆          ┆           ┆ f64       │
╞════════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ KQVEQLEK/2 ┆ -15.39728 ┆ 7.698642 ┆ -102.6623 ┆ … ┆ Q14152    ┆ -1.0     ┆ -1.0      ┆ 8.2194e-1 │
│            ┆ 4         ┆          ┆ 45        ┆   ┆           ┆          ┆           ┆ 1         │
│ ADHQPLTEA/ ┆ -14.39143 ┆ 7.195719 ┆ -99.93052 ┆ … ┆ P08865    ┆ -1.0     ┆ -1.0      ┆ 8.2194e-1 │
│ 2          ┆ 8         ┆          ┆ 6         ┆   ┆           ┆          ┆           ┆ 1         │
│ LFPEQQTK/2 ┆ 14.187453 ┆ 7.093726 ┆ 99.658141 ┆ … ┆ P05739    ┆ 1.0      ┆ 1.0       ┆ 8.2194e-1 │
│            ┆           ┆          ┆           ┆   ┆           ┆          ┆           ┆ 1         │
│ HLEMNPHFGS ┆ -13.92195 ┆ 6.960976 ┆ -97.46227 ┆ … ┆ Q08211    ┆ -1.0     ┆ -1.0      ┆ 8.2194e-1 │
│ HR/3       ┆ 2         ┆          ┆ 4         ┆   ┆           ┆          ┆           ┆ 1         │
│ RLEC(UniMo ┆ -13.81538 ┆ 6.90769  ┆ -97.26965 ┆ … ┆ Q3E793    ┆ -1.0     ┆ -1.0      ┆ 8.2194e-1 │
│ d:4)GFPDYK ┆ 1         ┆          ┆ 6         ┆   ┆           ┆          ┆           ┆ 1         │
│ /2         ┆           ┆          ┆           ┆   ┆           ┆          ┆           ┆           │
└────────────┴───────────┴──────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

#### Example: select precursor with min p-value for cut site

- In this case, the report should be first filtered to only keep those non-restricted cut site (i.e. non KR as defined when loading the report)

In [16]:
design = lipana.ComparisonDesign(exp_layout, (("H2d5_Y100", "H5_Y100"), ("H25_Y100", "H5_Y100")))
print(f"{design.pairwise_comparisons = }")

filters = ~pl.col("cut_site_is_restricted") & (~pl.col("mapped_species_from_peptide").str.contains(";", literal=True))

stats = lipana.do_stats_pipeline_pairwise(
    qdf=report.get_quant_data(
        entry_name="precursor",
        quant_name="precursor_quantity",
        main_df_entry_filter=filters,
    ),  # Note here no need to call `.df` because the requirement of filtering will make this function return a dataframe, instead of a `EntryQuantificationReport` object
    main_df=report.df.filter(filters),
    design=design,
    target_entry_col="cut_site",
    base_entry_col="precursor",
    group_entry_col="protein_group",  # Note this parameter is given because FDR control also can be done on the protein level
    pipeline="sel_min_p",
    return_chains=False,
)
sleep(0.1)
print("First 5 rows of the result:")
stats.head(5)

design.pairwise_comparisons = (('H2d5_Y100', 'H5_Y100'), ('H25_Y100', 'H5_Y100'))

Quantification file: /tmp/tmp2nucco9b.txt
All defined comparison pairs: c("H2d5_Y100", "H5_Y100")
Available comparison pairs: c("H2d5_Y100", "H5_Y100")
Comparing H2d5_Y100 vs H5_Y100
Output to /tmp/tmp2nucco9b.txt-limma_output.txt
Quantification file: /tmp/tmp5lq67_2z.txt
All defined comparison pairs: c("H25_Y100", "H5_Y100")
Available comparison pairs: c("H25_Y100", "H5_Y100")
Comparing H25_Y100 vs H5_Y100
Output to /tmp/tmp5lq67_2z.txt-limma_output.txt

First 5 rows of the result:

shape: (5, 15)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ precursor ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ group_sig ┆ adj_pvalu ┆ protein_g ┆ adj_pvalu │
│ ---       ┆ imma      ┆ ---      ┆ ---       ┆   ┆ n         ┆ e_exp_wis ┆ roup      ┆ e_group_w │
│ str       ┆ ---       ┆ f64      ┆ f64       ┆   ┆ ---       ┆ e         ┆ ---       ┆ ise       │
│           ┆ f64       ┆          ┆           ┆   ┆ f64       ┆ ---       ┆ str       ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆           ┆ f64       ┆           ┆ f64       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ KQVEQLEK/ ┆ -15.39728 ┆ 7.698642 ┆ -96.29664 ┆ … ┆ -1.0      ┆ 2.1368e-1 ┆ Q14152    ┆ 6.0964e-1 │
│ 2         ┆ 4         ┆          ┆ 6         ┆   ┆           ┆ 0         ┆           ┆ 2         │
│ ADHQPLTEA ┆ -14.39143 ┆ 7.195719 ┆ -93.03139 ┆ … ┆ -1.0      ┆ 2.1368e-1 ┆ P08865    ┆ 3.6495e-1 │
│ /2        ┆ 8         ┆          ┆           ┆   ┆           ┆ 0         ┆           ┆ 2         │
│ LFPEQQTK/ ┆ 14.187453 ┆ 7.093726 ┆ 92.570853 ┆ … ┆ 1.0       ┆ 2.1368e-1 ┆ P05739    ┆ 4.5954e-1 │
│ 2         ┆           ┆          ┆           ┆   ┆           ┆ 0         ┆           ┆ 3         │
│ YDSVEEGEK ┆ -16.43867 ┆ 8.219339 ┆ -89.85293 ┆ … ┆ -1.0      ┆ 2.1368e-1 ┆ P51659    ┆ 2.8931e-1 │
│ VVK/2     ┆ 7         ┆          ┆ 6         ┆   ┆           ┆ 0         ┆           ┆ 2         │
│ FTPGTFTNQ ┆ -14.54621 ┆ 7.273109 ┆ -89.27466 ┆ … ┆ -1.0      ┆ 2.1368e-1 ┆ P08865    ┆ 3.6495e-1 │
│ IQAA/2    ┆ 7         ┆          ┆ 8         ┆   ┆           ┆ 0         ┆           ┆ 2         │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Combine p-values

- This pipeline will do tests on base entry level, and use median to aggregate FC values, and Fisher's combined probability test to aggregate p-values
- The api of this method is similar as that for "select min p-value", with only one parameter changed
- Here will only show one example to do tests on peptides and aggregate to cut site

In [17]:
design = lipana.ComparisonDesign(exp_layout, (("H2d5_Y100", "H5_Y100"), ("H25_Y100", "H5_Y100")))
print(f"{design.pairwise_comparisons = }")

filters = ~pl.col("cut_site_is_restricted") & (~pl.col("mapped_species_from_peptide").str.contains(";", literal=True))

stats = lipana.do_stats_pipeline_pairwise(
    qdf=report.get_quant_data(
        entry_name="stripped_peptide",
        quant_name="peptide_quant_by_maxlfq_from_prec",  # this report is generated in one previous cell
        main_df_entry_filter=filters,
    ),  # Note here no need to call `.df` because the requirement of filtering will make this function return a dataframe, instead of a `EntryQuantificationReport` object
    main_df=report.df.filter(filters),
    design=design,
    target_entry_col="cut_site",
    base_entry_col="stripped_peptide",
    group_entry_col="protein_group",  # Note this parameter is given because FDR control also can be done on the protein level
    pipeline="combine_p",  # Note this parameter is different from that in the previous example
    return_chains=False,
)
sleep(0.1)
print("First 5 rows of the result:")
stats.head(5)

design.pairwise_comparisons = (('H2d5_Y100', 'H5_Y100'), ('H25_Y100', 'H5_Y100'))

Quantification file: /tmp/tmppkior05g.txt
All defined comparison pairs: c("H2d5_Y100", "H5_Y100")
Available comparison pairs: c("H2d5_Y100", "H5_Y100")
Comparing H2d5_Y100 vs H5_Y100
Output to /tmp/tmppkior05g.txt-limma_output.txt
Quantification file: /tmp/tmps8gjoksd.txt
All defined comparison pairs: c("H25_Y100", "H5_Y100")
Available comparison pairs: c("H25_Y100", "H5_Y100")
Comparing H25_Y100 vs H5_Y100
Output to /tmp/tmps8gjoksd.txt-limma_output.txt

First 5 rows of the result:

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cut_site  ┆ log2_fc   ┆ log2_fc_l ┆ pvalue    ┆ … ┆ adj_pvalu ┆ protein_g ┆ adj_pvalu ┆ pair     │
│ ---       ┆ ---       ┆ imma      ┆ ---       ┆   ┆ e_exp_wis ┆ roup      ┆ e_group_w ┆ ---      │
│ str       ┆ f32       ┆ ---       ┆ f64       ┆   ┆ e         ┆ ---       ┆ ise       ┆ str      │
│           ┆           ┆ f64       ┆           ┆   ┆ ---       ┆ str       ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ P33331-33 ┆ 0.583285  ┆ 0.585327  ┆ 0.007472  ┆ … ┆ 0.030339  ┆ P33331    ┆ 0.112078  ┆ H2d5_Y10 │
│ _34       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0_vs_H5_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Y100     │
│ P13639-65 ┆ -1.412413 ┆ -1.42665  ┆ 0.00038   ┆ … ┆ 0.001907  ┆ P13639    ┆ 0.0005    ┆ H2d5_Y10 │
│ 2_653     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0_vs_H5_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Y100     │
│ P05759-10 ┆ -0.072209 ┆ -0.118206 ┆ 0.720269  ┆ … ┆ 0.964309  ┆ P05759    ┆ 0.977361  ┆ H2d5_Y10 │
│ 4_105     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0_vs_H5_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Y100     │
│ O94927-48 ┆ -10.41852 ┆ -10.35127 ┆ 1.2109e-7 ┆ … ┆ 7.8406e-7 ┆ O94927    ┆ 1.2109e-7 ┆ H2d5_Y10 │
│ 1_482     ┆ 6         ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆ 0_vs_H5_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Y100     │
│ P02400-73 ┆ 0.115277  ┆ 0.108314  ┆ 0.556856  ┆ … ┆ 0.905096  ┆ P02400    ┆ 0.953457  ┆ H2d5_Y10 │
│ _74       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0_vs_H5_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Y100     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Direct tests on target level

- This method will directly do tests on the expected target entry level, and the input should of course be the quantification matrix that is on the target entry level
- Here shows the tests on stripped peptides that are fully-specific

In [18]:
design = lipana.ComparisonDesign(exp_layout, (("H2d5_Y100", "H5_Y100"), ("H25_Y100", "H5_Y100")))
print(f"{design.pairwise_comparisons = }")

filters = (pl.col("peptide_enzymatic_specificity") == "fully_specific") & (
    ~pl.col("mapped_species_from_peptide").str.contains(";", literal=True)
)

stats = lipana.do_stats_pipeline_pairwise(
    qdf=report.get_quant_data(
        entry_name="stripped_peptide",
        quant_name="peptide_quant_by_maxlfq_from_prec",  # this report is generated in one previous cell
        main_df_entry_filter=filters,
    ),
    main_df=report.df.filter(filters),
    design=design,
    target_entry_col="stripped_peptide",
    base_entry_col=None,  # Note in this case, `base_entry_col` should be None
    group_entry_col="protein_group",
    pipeline="direct_test",  # Note this parameter is different from that in the previous example
    return_chains=False,
)
sleep(0.1)
print("First 5 rows of the result:")
stats.head(5)

design.pairwise_comparisons = (('H2d5_Y100', 'H5_Y100'), ('H25_Y100', 'H5_Y100'))

Quantification file: /tmp/tmp65e4al82.txt
All defined comparison pairs: c("H2d5_Y100", "H5_Y100")
Available comparison pairs: c("H2d5_Y100", "H5_Y100")
Comparing H2d5_Y100 vs H5_Y100
Output to /tmp/tmp65e4al82.txt-limma_output.txt
Quantification file: /tmp/tmpbza64njh.txt
All defined comparison pairs: c("H25_Y100", "H5_Y100")
Available comparison pairs: c("H25_Y100", "H5_Y100")
Comparing H25_Y100 vs H5_Y100
Output to /tmp/tmpbza64njh.txt-limma_output.txt

First 5 rows of the result:

shape: (5, 12)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ stripped_ ┆ log2_fc_l ┆ AveExpr  ┆ t         ┆ … ┆ log2_fc   ┆ adj_pvalu ┆ protein_g ┆ adj_pvalu │
│ peptide   ┆ imma      ┆ ---      ┆ ---       ┆   ┆ ---       ┆ e_exp_wis ┆ roup      ┆ e_group_w │
│ ---       ┆ ---       ┆ f64      ┆ f64       ┆   ┆ f32       ┆ e         ┆ ---       ┆ ise       │
│ str       ┆ f64       ┆          ┆           ┆   ┆           ┆ ---       ┆ str       ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆           ┆ f64       ┆           ┆ f64       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ RLECGFPDY ┆ -13.81538 ┆ 6.90769  ┆ -104.0188 ┆ … ┆ -13.81599 ┆ 7.6420e-1 ┆ Q3E793    ┆ 3.8816e-1 │
│ K         ┆ 1         ┆          ┆ 98        ┆   ┆ 6         ┆ 0         ┆           ┆ 2         │
│ EIYHFTLEK ┆ -14.35316 ┆ 7.176582 ┆ -103.0742 ┆ … ┆ -14.35591 ┆ 7.6420e-1 ┆ Q9BT78    ┆ 1.0344e-1 │
│           ┆ 5         ┆          ┆ 31        ┆   ┆ 3         ┆ 0         ┆           ┆ 1         │
│ QWGWTQGR  ┆ -14.61908 ┆ 7.30954  ┆ -100.3802 ┆ … ┆ -14.62406 ┆ 7.6420e-1 ┆ P18621    ┆ 1.4944e-1 │
│           ┆           ┆          ┆ 4         ┆   ┆ 6         ┆ 0         ┆           ┆ 1         │
│ TDGKVFQFL ┆ -14.14959 ┆ 7.074797 ┆ -100.2259 ┆ … ┆ -14.15304 ┆ 7.6420e-1 ┆ P83731    ┆ 1.0070e-1 │
│ NAK       ┆ 5         ┆          ┆ 04        ┆   ┆ 7         ┆ 0         ┆           ┆ 1         │
│ SADLYKDR  ┆ -13.15159 ┆ 6.575795 ┆ -98.23687 ┆ … ┆ -13.15254 ┆ 7.6420e-1 ┆ Q9HBM1    ┆ 2.8971e-1 │
│           ┆ 1         ┆          ┆ 7         ┆   ┆ 7         ┆ 0         ┆           ┆ 2         │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Customized pipeline